# Generated by Django 2.2.4 on 2020-04-20 05:41

import backend_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to=backend_app.models.scramble_filename),
        ),
    ]
